name: kensui
description: "懸垂回数を記録・管理するアプリケーション"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.66.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  provider: ^6.1.1
  path_provider: ^2.1.2
  sensors_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
