name: Flutter CI

on:
  push:
    branches:
      - develop
      - main
      - fix_*
      - setup_*
  pull_request:
    branches:
      - develop
      - main
      - fix_*
      - setup_*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
    
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true
    
      - name: Install dependencies
        run: flutter pub get
      
      - name: Analyze project source
        run: flutter analyze
      
      - name: Run tests
        run: flutter test
      
      - name: Build Web
        run: flutter build web --release
      
      - name: Setup Android build
        run: |
          flutter config --android-sdk $ANDROID_SDK_ROOT
          flutter doctor -v
          flutter clean
          cd android
          ./gradlew clean
          cd ..
        
      - name: Build Android
        run: |
          flutter build apk --debug # まずdebugビルドを試す
          flutter build apk --release
          flutter build appbundle --release